# INSURANCE ANALYSIS PROJECT

CREATE DATABASE Insurance_Analysis;

DELIMITER //
CREATE PROCEDURE KPI_FOR_PROJECT (IN INCOMECLASS VARCHAR (50))
BEGIN

DECLARE BUGDET_VALUE DOUBLE;

SET @CROSS_SELL_TARGET = (SELECT SUM(Cross_sell_bugdet) FROM individual_budgets);
SET @NEW_TARGET = (SELECT SUM(New_Budget) from individual_budgets);
SET @RENEWAL_TARGET = (SELECT SUM(Renewal_Budget) FROM individual_budgets);

SET @INVOICE_VALUE = (SELECT SUM(Amount) FROM invoice WHERE income_class=INCOMECLASS);
SET @ACHIEVED_VALUE = ((SELECT SUM(Amount) FROM brokerage WHERE income_class=INCOMECLASS) +
                      (SELECT SUM(Amount) FROM fees WHERE income_class=INCOMECLASS));
				
IF INCOMECLASS = "Cross Sell" THEN SET BUGDET_VALUE = @CROSS_SELL_TARGET;
ELSEIF INCOMECLASS = "New" THEN SET BUGDET_VALUE = @NEW_TARGET;
ELSEIF INCOMECLASS = "Renewal" THEN SET BUGDET_VALUE = @RENEWAL_TARGET;
ELSE SET BUGDET_VALUE = 0;
END IF;

SET @PLACED_ACHVMENT = (SELECT CONCAT(FORMAT((@ACHIEVED_VALUE / BUGDET_VALUE)*100,2),'%'));
SET @INVOICE_ACHVMENT = (SELECT CONCAT(FORMAT((@INVOICE_VALUE / BUGDET_VALUE)*100,2),'%'));

SELECT INCOMECLASS, FORMAT(BUGDET_VALUE,0) AS TARGET,
					FORMAT(@INVOICE_VALUE,0) AS INVOICE,
                    FORMAT(@ACHIEVED_VALUE,2) AS ACHIEVED,
                    @PLACED_ACHVMENT AS PLACED_ACHIEVEMENT_PERCENTAGE,
                    @INVOICE_ACHVMENT AS INVOICE_ACHIEVEMENT_PERCETAGE;
END //
DELIMITER ;

CALL KPI_FOR_PROJECT("New");







SET @SUM_OF_CROSSBUD = (select Sum(Cross_Sell_bugdet) from individual_budgets);

select @SUM_OF_CROSSBUD;

SET @ACHIEVED_CROSS = (select Sum(Amount) from brokerage where income_class = "Cross Sell");

select @SUM_OF_CROSSBUD/@ACHIEVED_CROSS;
